@startuml Login
actor User
participant UserController
participant UserService
participant UserRepository
participant AuthenticationSystem
database SqlServer

activate User
User -> UserController: login(email, password)
activate UserController
UserController -> UserService: login(email, password)
activate UserService
UserService -> UserRepository: findByemail(email)
activate UserRepository
UserRepository -> SqlServer: SELECT * FROM User WHERE Email = email
activate SqlServer
SqlServer --> UserRepository: user
deactivate SqlServer
UserRepository --> UserService: user
deactivate UserRepository
UserService -> AuthenticationSystem: verifyCredentials(email, password)
activate AuthenticationSystem
AuthenticationSystem -> SqlServer: SELECT Password, PasswordSalt FROM User WHERE Email = email
activate SqlServer
SqlServer --> AuthenticationSystem: result
deactivate SqlServer
AuthenticationSystem --> UserService: result
deactivate AuthenticationSystem
UserService -> UserController: result
deactivate UserService
UserController -> User: result
deactivate UserController
User --> UserController: result
deactivate User
@enduml