@startuml Login
actor User
participant LoginScreen
participant UserController
participant UserService
participant UserRepository
participant PasswordHelper
participant TokenService
database SqlServer

activate User
    User -> LoginScreen: Input Login information
    activate LoginScreen
        LoginScreen -> UserController: Login(LoginRequest)
        activate UserController
            UserController -> UserService: LoginAsync(LoginRequest)
            activate UserService
                UserService -> UserRepository: FindByEmail(Email)
                activate UserRepository
                    UserRepository -> SqlServer: executeQuery()
                    activate SqlServer
                        SqlServer --> UserRepository: response
                    deactivate SqlServer
                    UserRepository --> UserService: response
                deactivate UserRepository
                alt Email doesn't exist 
                    UserService --> UserController: return error code
                else Email exist
                    UserService -> PasswordHelper: HashUsingPbkdf2(Password, PasswordSalt)
                    activate PasswordHelper
                        PasswordHelper --> UserService: response
                    deactivate PasswordHelper
                    alt Password and passwordHash doesn't match 
                        UserService --> UserController: return error code
                    else Password and passwordHash matched
                        UserService -> TokenService: GenerateTokensAsync(UserId)
                        activate TokenService
                            TokenService --> UserService: response
                        deactivate TokenService
                        UserService --> UserController: return success code
                    end
                end
            deactivate UserService
            UserController --> LoginScreen: response
        deactivate UserController
        LoginScreen --> User: display message
    deactivate LoginScreen
deactivate User
@enduml