@startuml List Joined League
actor ClubManager #Aquamarine
participant ListJoinedLeagueScreen
participant ParticipationController
participant ParticipationService
participant ParticipationRepository
database SqlServer

activate ClubManager
    ClubManager -> ListJoinedLeagueScreen: view list joined League
    activate ListJoinedLeagueScreen
        ListJoinedLeagueScreen -> ParticipationController: GetListJoinedLeague()
        activate ParticipationController
            ParticipationController -> ParticipationService: GetListJoinedLeague(UserID)
            activate ParticipationService
                ParticipationService -> ParticipationRepository: FindByUserId()
                note right: Club joined leagues that been confirmed \n by league managers only
                activate ParticipationRepository
                    ParticipationRepository -> SqlServer : executeQuery()
                    activate SqlServer
                        SqlServer --> ParticipationRepository: response
                    deactivate SqlServer
                    ParticipationRepository --> ParticipationService: response
                deactivate ParticipationRepository
                ParticipationService --> ParticipationController: response
            deactivate ParticipationService
            ParticipationController --> ListJoinedLeagueScreen: data
        deactivate ParticipationController
        ListJoinedLeagueScreen --> ClubManager: Display data
    deactivate ListJoinedLeagueScreen
deactivate ClubManager
@enduml