@startuml View League Statistic Type League (Guest)
actor User
participant LeagueStatisticScreen
participant LeagueController
participant LeagueService
participant LeagueRepository
database SqlServer

activate User 
    User -> LeagueStatisticScreen: View League statistic League
    activate LeagueStatisticScreen
        LeagueStatisticScreen -> LeagueController: GetLeagueStatistic(leagueId)
        activate LeagueController
            LeagueController ->LeagueService: GetLeagueStatisticTypeLeague(leagueId)
            activate LeagueService
                LeagueService -> LeagueRepository: FindByLeagueId()
                activate LeagueRepository
                    LeagueRepository -> SqlServer: executeQuery()
                    activate SqlServer
                        SqlServer --> LeagueRepository: response
                    deactivate SqlServer
                    LeagueRepository --> LeagueService: response
                deactivate LeagueRepository
                alt League does not exist 
                    LeagueService --> LeagueController: return error code
                else League Type is not League
                    LeagueService --> LeagueController: return error code
                else all condition valid
                    LeagueService -> LeagueService: Order statistic by point and GD -> standings
                    group get top event
                        LeagueService -> LeagueService: GetLeagueTopEvent(leagueId)
                    end
                    LeagueService --> LeagueController: response(standings, topevent)
                end
            deactivate LeagueService
            LeagueController --> LeagueStatisticScreen: data
        deactivate LeagueController
        LeagueStatisticScreen --> User: Display data
    deactivate LeagueStatisticScreen
deactivate User
@enduml