@startuml ViewPlayerList(Club)
actor ClubManager #Aquamarine
participant PlayerListScreen
participant PlayerController
participant PlayerService
participant PlayerRepository
database SqlServer

activate ClubManager
    ClubManager -> PlayerListScreen: Input name to search player
    activate PlayerListScreen
        PlayerListScreen -> PlayerController: GetListPlayerFilter(ListPlayerFilterRequest)
        activate PlayerController
            PlayerController -> PlayerService: GetListPlayerFilter(request)
            activate PlayerService
                PlayerService -> PlayerRepository: FindByCondition(PlayerName/NickName)
                activate PlayerRepository
                    PlayerRepository -> SqlServer: executeQuery()
                    activate SqlServer
                        SqlServer --> PlayerRepository : response
                    deactivate SqlServer
                    PlayerRepository --> PlayerService: response
                deactivate PlayerRepository
                PlayerService --> PlayerController: response
            deactivate PlayerService
            PlayerController --> PlayerListScreen: response
        deactivate PlayerController
        PlayerListScreen --> ClubManager: data
    deactivate PlayerListScreen
deactivate ClubManager 
@enduml